#!/bin/bash

case $# in
1)

 case $1 in
 LittleEndian)

  # Clean
  if test -f tv.bv32
  then
  \rm tv.bv32
  fi
  if test -f tv.bv32.raw
  then
  \rm tv.bv32.raw
  fi
  if test -f tv.bv32.bfe10.raw
  then
  \rm tv.bv32.bfe10.raw
  fi

  # Process codec
  BroadVoice32 enc tv.raw tv.bv32
  BroadVoice32 dec tv.bv32 tv.bv32.raw
  BroadVoice32 dec tv.bfe10.bv32 tv.bv32.bfe10.raw

  checksum=0;
  if test -n "`cmp tv.bv32 tv.bv32.ref`"
  then
  checksum=`expr $checksum + 1`
  fi
  if test -n "`cmp tv.bv32.raw tv.bv32.ref.raw`"
  then
  checksum=`expr $checksum + 1`
  fi
  if test -n "`cmp tv.bv32.bfe10.raw tv.bv32.bfe10.ref.raw`"
  then
  checksum=`expr $checksum + 1`
  fi

  if test ! -e tv.bv32
  then
  checksum=-1;
  fi
  if test ! -e tv.bv32.raw
  then
  checksum=-1;
  fi
  if test ! -e tv.bv32.bfe10.raw
  then
  checksum=-1;
  fi

  case $checksum in 
  -1)
   echo "  *************************************************"
   echo "  * WARNING: Missing files - something went wrong *"
   echo "  * Correct Endian format entered?                *"
   echo "  *************************************************"
   echo ""
  ;;
  0)
   echo "  **************************************************************************"
   echo "  * CONGRATULATIONS: Your compilation passed the simple functionality test *"
   echo "  **************************************************************************"
   echo ""
  \rm tv.bv32 tv.bv32.raw tv.bv32.bfe10.raw
  ;;
  *)
   echo "  ************************************************************************"
   echo "  * WARNING: Your compilation DID NOT pass the simple functionality test *"
   echo "  * Correct Endian format entered?                                       *"
   echo "  ************************************************************************"
   echo ""
  ;;
  esac

 ;;
 BigEndian)

  # Clean
  if test -f tvbe.bv32
  then
  \rm tvbe.bv32
  fi
  if test -f tvbe.bv32.raw
  then
  \rm tvbe.bv32.raw
  fi
  if test -f tvbe.bv32.bfe10.raw
  then
  \rm tvbe.bv32.bfe10.raw
  fi

  # Byte-swab little endian audio and G.192 bitstream reference files
  dd conv=swab if=tv.raw                of=tvbe.raw
  dd conv=swab if=tv.bv32.ref           of=tvbe.bv32.ref
  dd conv=swab if=tv.bv32.ref.raw       of=tvbe.bv32.ref.raw
  dd conv=swab if=tv.bfe10.bv32         of=tvbe.bfe10.bv32
  dd conv=swab if=tv.bv32.bfe10.ref.raw of=tvbe.bv32.bfe10.ref.raw

  # Process codec
  BroadVoice32 enc tvbe.raw tvbe.bv32
  BroadVoice32 dec tvbe.bv32 tvbe.bv32.raw
  BroadVoice32 dec tvbe.bfe10.bv32 tvbe.bv32.bfe10.raw

  checksum=0;
  if test -n "`cmp tvbe.bv32 tvbe.bv32.ref`"
  then
  checksum=`expr $checksum + 1`
  fi
  if test -n "`cmp tvbe.bv32.raw tvbe.bv32.ref.raw`"
  then
  checksum=`expr $checksum + 1`
  fi
  if test -n "`cmp tvbe.bv32.bfe10.raw tvbe.bv32.bfe10.ref.raw`"
  then
  checksum=`expr $checksum + 1`
  fi

  if test ! -e tvbe.bv32
  then
  checksum=-1;
  fi
  if test ! -e tvbe.bv32.raw
  then
  checksum=-1;
  fi
  if test ! -e tvbe.bv32.bfe10.raw
  then
  checksum=-1;
  fi

  case $checksum in 
  -1)
   echo "  *************************************************"
   echo "  * WARNING: Missing files - something went wrong *"
   echo "  * Correct Endian format entered?                *"
   echo "  *************************************************"
   echo ""
  ;;
  0)
   echo "  **************************************************************************"
   echo "  * CONGRATULATIONS: Your compilation passed the simple functionality test *"
   echo "  **************************************************************************"
   echo ""
   \rm tvbe.bv32 tvbe.bv32.raw tvbe.bv32.bfe10.raw tvbe.raw tvbe.bv32.ref tvbe.bv32.ref.raw tvbe.bfe10.bv32 tvbe.bv32.bfe10.ref.raw
  ;;
  *)
   echo "  ************************************************************************"
   echo "  * WARNING: Your compilation DID NOT pass the simple functionality test *"
   echo "  * Correct Endian format entered?                                       *"
   echo "  ************************************************************************"
   echo ""
  ;;
  esac

 ;;
 CleanAll)
  if test -f tv.bv32
  then
  \rm tv.bv32
  fi
  if test -f tv.bv32.raw
  then
  \rm tv.bv32.raw
  fi
  if test -f tv.bv32.bfe10.raw
  then
  \rm tv.bv32.bfe10.raw
  fi
  if test -f tvbe.bv32
  then
  \rm tvbe.bv32
  fi
  if test -f tvbe.bv32.raw
  then
  \rm tvbe.bv32.raw
  fi
  if test -f tvbe.bv32.bfe10.raw
  then
  \rm tvbe.bv32.bfe10.raw
  fi
  if test -f tvbe.raw
  then
  \rm tvbe.raw
  fi
  if test -f tvbe.bv32.ref
  then
  \rm tvbe.bv32.ref
  fi
  if test -f tvbe.bv32.ref.raw
  then
  \rm tvbe.bv32.ref.raw
  fi
  if test -f tvbe.bfe10.bv32
  then
  \rm tvbe.bfe10.bv32
  fi
  if test -f tvbe.bv32.bfe10.ref.raw
  then
  \rm tvbe.bv32.bfe10.ref.raw
  fi
  if test -f BroadVoice32
  then
  \rm BroadVoice32
  fi
  if test -f BroadVoice32.exe
  then
  \rm BroadVoice32.exe
  fi
 
 ;;
 *)
  echo "Invalid Endian format: $1"
 ;;
 esac

;;
*)
 echo "Usage: $0 LittleEndian/BigEndian/CleanAll"
;;
esac
